using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Drawing.Printing;


namespace Ticari
{
    public partial class Irsaliye : Form
    {
       
        public Irsaliye()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
           
        }

        SqlBaglantisi bgl = new SqlBaglantisi();

        public string metin1;
        private void FrmNotDetay_Load(object sender, EventArgs e)
        {
            gridControl1.Text = metin1;
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void Irsaliye_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dboTicariOtomosyonDataSet9.TBL_FATURADETAY' table. You can move, or remove it, as needed.
            this.tBL_FATURADETAYTableAdapter.Fill(this.dboTicariOtomosyonDataSet9.TBL_FATURADETAY);

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
           
        }
        

        

       
    }
}
